-- ═══════════════════════════════════════════════════════════════════════
-- aufguss.world — dane startowe (WYGENEROWANE: node supabase/generate-seed.js)
-- Nie edytować ręcznie: zmiany nanosić w data/*.js i wygenerować ponownie.
-- ═══════════════════════════════════════════════════════════════════════
begin;

-- Obiekty (107)
insert into public.venues (id, slug, name, country, country_code, city, lat, lng, website) values
  (1, 'sommer-residence-hotel-spa', 'Sommer Residence Hotel & SPA', 'Polska', 'pl', null, 50.944809, 18.224132, 'http://sommerresidence.pl/'),
  (2, 'saunowy-staw', 'Saunowy Staw', 'Polska', 'pl', null, 54.432257, 18.294695, 'https://www.saunowystaw.pl/'),
  (3, 'rzeka-miodu', 'Rzeka Miodu', 'Polska', 'pl', null, 51.091321, 18.658949, 'http://rzekamiodu.pl/'),
  (4, 'wodny-park-tychy', 'Wodny Park Tychy', 'Polska', 'pl', null, 50.103242, 18.977663, 'http://www.wodnypark.tychy.pl/'),
  (5, 'park-wodny-trzy-fale-slupsk', 'Park Wodny "Trzy Fale" Słupsk', 'Polska', 'pl', null, 54.481326, 17.011838, 'https://www.trzyfale.slupsk.pl/'),
  (6, 'nadbuzanska-cisza', 'Nadbużańska Cisza', 'Polska', 'pl', null, 50.948611, 23.9731, 'https://www.nadbuzanska-cisza.com.pl/'),
  (7, 'hotel-azzun-orient-spa-wellness', 'Hotel Azzun Orient SPA & Wellness', 'Polska', 'pl', null, 53.828819, 20.822112, 'https://www.azzun.pl/'),
  (8, 'swiatynia-ognia-i-wody', 'Świątynia Ognia i Wody', 'Polska', 'pl', null, 53.423155, 18.336058, 'http://www.swiatyniaogniaiwody.pl/'),
  (9, 'termy-maltanskie', 'Termy Maltańskie', 'Polska', 'pl', null, 52.40528, 16.974252, 'http://www.termymaltanskie.com.pl/'),
  (10, 'per-natura-wioska-saunowa', 'Per Natura Wioska Saunowa', 'Polska', 'pl', null, 52.418707, 21.358354, 'https://www.facebook.com/p/Per-Natura-Wioska-Saunowa-100064160469174/?locale=pl_PL'),
  (11, 'moje-male-bieszczady', 'Moje Małe Bieszczady', 'Polska', 'pl', null, 49.784499, 21.622653, 'https://www.mojemalebieszczady.pl'),
  (12, 'termy-krakowskie-blonia', 'Termy Krakowskie Błonia', 'Polska', 'pl', null, 50.06233, 19.910489, 'http://www.termykrakowskie.pl/'),
  (13, 'termy-rzymskie', 'Termy Rzymskie', 'Polska', 'pl', null, 50.308109, 19.069891, 'http://termyrzymskie.pl/'),
  (14, 'chocholowskie-termy', 'Chochołowskie Termy', 'Polska', 'pl', null, 49.351825, 19.82312, 'http://chocholowskietermy.pl/'),
  (15, 'park-wodny-tarnowskie-gory', 'Park Wodny Tarnowskie Góry', 'Polska', 'pl', null, 50.438744, 18.837381, 'http://www.parkwodny.com.pl/'),
  (16, 'aquapark-reda', 'Aquapark Reda', 'Polska', 'pl', null, 54.594674, 18.36612, 'https://www.aquaparkreda.pl/'),
  (17, 'sauny-swietokrzyskie-binkowski-resort', 'Sauny Świętokrzyskie Bińkowski Resort', 'Polska', 'pl', null, 50.854128, 20.608393, 'https://basenytropikalne.pl/'),
  (18, 'aquapark-wroclaw', 'Aquapark Wrocław', 'Polska', 'pl', null, 51.091046, 17.032217, 'https://aquapark.wroc.pl/'),
  (19, 'aquapark-fala', 'Aquapark Fala', 'Polska', 'pl', null, 51.764155, 19.421186, 'https://aquapark.lodz.pl/?utm_source=Moja-Firma&utm_medium=Strona'),
  (20, 'suntago', 'Suntago', 'Polska', 'pl', null, 51.987697, 20.459783, 'https://parkofpoland.com/'),
  (21, 'saunowe-zacisze', 'Saunowe Zacisze', 'Polska', 'pl', null, 52.487952, 19.04961, 'https://www.facebook.com/LewandoweZacisze'),
  (22, 'zdrowo-nagrzani', 'Zdrowo Nagrzani', 'Polska', 'pl', null, 52.141036, 21.263179, 'https://zdrowonagrzani.pl/'),
  (23, 'destresso', 'Destresso', 'Polska', 'pl', null, 51.738785, 19.461924, 'http://www.destresso.pl/'),
  (24, 'gorko-spa', 'Gorko SPA', 'Polska', 'pl', null, 50.103389, 18.753551, 'https://www.facebook.com/profile.php?id=100088870312537'),
  (25, 'termy-goracy-potok', 'Termy Gorący Potok', 'Polska', 'pl', null, 49.399958, 20.022592, 'https://goracypotok.pl/'),
  (26, 'me-najwyzszy-poziom-saunowania', 'ME Najwyższy poziom saunowania', 'Polska', 'pl', null, 53.732541, 19.831833, 'https://www.facebook.com/profile.php?id=100089710347555'),
  (27, 'hot-spot-saunarium-krakow', 'HOT SPOT Saunarium Kraków', 'Polska', 'pl', null, 50.043351, 19.969661, 'https://hotspot.com.pl/'),
  (28, 'grzanki-pod-lowiczem', 'Grzanki Pod Łowiczem', 'Polska', 'pl', null, 52.045508, 19.947929, 'https://www.facebook.com/groups/984946102081889/'),
  (29, 'wanga-sauna-spa', 'Wanga Sauna & Spa', 'Polska', 'pl', null, 54.277411, 18.551249, 'https://saunawanga.pl/'),
  (30, 'spa-kruteczkowo-lesne-saunowanie', 'Spa Kruteczkowo - Leśne Saunowanie', 'Polska', 'pl', null, 52.824974, 16.403418, 'https://www.facebook.com/p/Leśne-Saunowanie-Kruteczkowo-100082948461349/?locale=pl_PL'),
  (31, 'chata-raroga-sauna-plenerowa-dzikie-spa', 'Chata Raroga - Sauna Plenerowa Dzikie Spa', 'Polska', 'pl', null, 51.302145, 20.904758, 'https://www.chatararoga.pl/'),
  (32, 'aquapalace-praha', 'Aquapalace Praha', 'Czechy', 'cz', null, 50.007469, 14.571526, 'https://www.aquapalace.cz/'),
  (33, 'saunas-vltava', 'Saunas Vltava', 'Czechy', 'cz', null, 50.047189, 14.413545, 'https://saunyvltava.cz/'),
  (34, 'infinit-sen', 'Infinit Sen', 'Czechy', 'cz', null, 49.897396, 14.714615, 'https://sen.infinit.cz/'),
  (35, 'aphrodite-spa-spa-rajecke-teplice', 'Aphrodite Spa - Spa Rajecke Teplice', 'Słowacja', 'sk', null, 49.129328, 18.682215, 'http://www.spa.sk/'),
  (36, 'saunia-thermal-resort', 'Saunia Thermal Resort', 'Czechy', 'cz', null, 50.228999, 12.878052, 'https://www.thermal.saunia.cz/'),
  (37, 'melori-aqua-spa', 'MELORI aqua & spa', 'Czechy', 'cz', null, 50.150682, 16.814974, 'https://www.melori.cz/'),
  (38, 'wodny-park-besenova', 'Wodny Park Bešeňová', 'Słowacja', 'sk', null, 49.100211, 19.43472, 'http://www.besenova.sk/'),
  (39, 'infinit-maximus-brno', 'Infinit Maximus Brno', 'Czechy', 'cz', null, 49.243353, 16.516041, 'https://maximus.infinit.cz/'),
  (40, 'infinit-relaxacni-centrum', 'Infinit relaxační centrum', 'Czechy', 'cz', null, 50.101189, 14.483401, 'https://step.infinit.cz/'),
  (41, 'saunia-letmo-brno', 'Saunia LETMO Brno', 'Czechy', 'cz', null, 49.191679, 16.612558, 'https://www.saunia.cz/'),
  (42, 'mediterana', 'Mediterana', 'Niemcy', 'de', null, 50.964995, 7.136539, 'https://www.mediterana.de/'),
  (43, 'kristall-rheinpark-therme-bad-honningen-gmbh', 'Kristall Rheinpark-Therme Bad Hönningen GmbH', 'Niemcy', 'de', null, 50.511555, 7.308192, 'https://www.kristall-rheinpark-therme.de/'),
  (44, 'thermen-badewelt-sinsheim', 'Thermen & Badewelt Sinsheim', 'Niemcy', 'de', null, 49.236075, 8.884299, 'http://www.badewelt-sinsheim.de/'),
  (45, 'kisssalis-therme-bad-kissingen', 'KissSalis Therme Bad Kissingen', 'Niemcy', 'de', null, 50.188526, 10.063723, 'http://www.kisssalis.de/'),
  (46, 'thermenatur-bad-rodach', 'ThermeNatur Bad Rodach', 'Niemcy', 'de', null, 50.31927, 10.765113, 'https://www.therme-natur.de/'),
  (47, 'carolus-thermen', 'Carolus Thermen', 'Niemcy', 'de', null, 50.782937, 6.097521, 'https://www.carolus-thermen.de/'),
  (48, 'obermain-therme', 'Obermain Therme', 'Niemcy', 'de', null, 50.110173, 10.989405, 'https://www.obermaintherme.de/saunaland/termine-2/'),
  (49, 'kristall-palm-beach', 'Kristall Palm Beach', 'Niemcy', 'de', null, 49.4067, 11.006322, 'http://www.palm-beach.de/'),
  (50, 'termy-erding', 'Termy Erding', 'Niemcy', 'de', null, 48.290231, 11.888578, 'https://www.therme-erding.de/'),
  (51, 'kristall-therme-trimini-kochel-am-see', 'Kristall Therme trimini Kochel am See', 'Niemcy', 'de', null, 47.655948, 11.354286, 'http://www.kristall-trimini.de/'),
  (52, 'meri-sauna-kulkwitzer-see-gmbh', 'Meri Sauna Kulkwitzer See GmbH', 'Niemcy', 'de', null, 51.306857, 12.239606, 'http://www.meri-sauna.de/'),
  (53, 'badegarten-eibenstock-gmbh', 'Badegärten Eibenstock GmbH', 'Niemcy', 'de', null, 50.505178, 12.598408, 'https://www.badegaerten.de/'),
  (54, 'spreewelten-bad-lubbenau', 'Spreewelten Bad Lübbenau', 'Niemcy', 'de', null, 51.857057, 13.952863, 'http://www.spreewelten.de/'),
  (55, 'satama-sauna-resort-spa', 'SATAMA SAUNA RESORT & SPA', 'Niemcy', 'de', null, 52.21502, 14.01027, 'https://www.satama-saunapark.de/'),
  (56, 'monte-mare-seesauna-in-tegernsee', 'monte mare Seesauna in Tegernsee', 'Niemcy', 'de', null, 47.715239, 11.753491, 'http://www.monte-mare.de/tegernsee'),
  (57, 'saarowtherme', 'SaarowTherme', 'Niemcy', 'de', null, 52.291017, 14.060493, 'https://therme.bad-saarow.de/'),
  (58, 'havel-therme', 'Havel-Therme', 'Niemcy', 'de', null, 52.399407, 12.924038, 'http://www.havel-therme.de/'),
  (59, 'therme-euskirchen', 'Therme Euskirchen', 'Niemcy', 'de', null, 50.667, 6.802423, 'https://www.badewelt-euskirchen.de/de'),
  (60, 'sieben-welten-therme-spa-resort', 'Sieben Welten Therme & Spa Resort', 'Niemcy', 'de', null, 50.53803, 9.72332, 'http://www.siebenwelten.de/'),
  (61, 'vabali', 'Vabali', 'Niemcy', 'de', null, 52.528545, 13.359277, 'https://www.vabali.de/berlin/'),
  (62, 'sauna-wasserwelten-bahia', 'Sauna- & Wasserwelten Bahia', 'Niemcy', 'de', null, 51.86223, 6.6097, 'http://www.bahia.de/oeffnungszeiten'),
  (63, 'vabali-spa-hamburg', 'Vabali Spa Hamburg', 'Niemcy', 'de', null, 53.535729, 10.207791, 'https://www.vabali.de/hamburg/'),
  (64, 'thermen-badewelt-sinsheim-64', 'Thermen & Badewelt Sinsheim', 'Niemcy', 'de', null, 49.236075, 8.884299, 'http://www.badewelt-sinsheim.de/'),
  (65, 'vitasol-therme-gmbh', 'VitaSol Therme GmbH', 'Niemcy', 'de', null, 52.096006, 8.752592, 'http://www.vitasol.de/'),
  (66, 'therme-bad-worishofen', 'THERME Bad Wörishofen', 'Niemcy', 'de', null, 48.021135, 10.590433, 'http://www.therme-badwoerishofen.de/'),
  (67, 'tropical-islands', 'Tropical Islands', 'Niemcy', 'de', null, 52.038993, 13.748653, 'https://www.tropical-islands.de/?utm_id=GMBtraffic&utm_medium=OrganicGMB&utm_source=google'),
  (68, 'therme-lindau', 'Therme Lindau', 'Niemcy', 'de', null, 47.548846, 9.716436, 'http://www.therme-lindau.com/'),
  (69, 'kristall-kur-und-gradier-therme-bad-wilsnack', 'Kristall Kur- und Gradier-Therme Bad Wilsnack', 'Niemcy', 'de', null, 52.963512, 11.948233, 'http://www.kristalltherme-bad-wilsnack.de/'),
  (70, 'royal-crystal-therme', 'Royal Crystal Therme', 'Niemcy', 'de', null, 52.397532, 9.601045, 'http://www.kristalltherme-seelze.de/'),
  (71, 'cambomare-indoor-pool-and-sauna-world', 'CamboMare indoor pool and sauna world', 'Niemcy', 'de', null, 47.719657, 10.292288, 'http://www.cambomare.de/'),
  (72, 'konigliche-kristall-therme-am-kurpark-schwangau', 'Königliche Kristall-Therme am Kurpark Schwangau', 'Niemcy', 'de', null, 47.575627, 10.726526, 'http://www.kristalltherme-schwangau.de/'),
  (73, 'the-white-oak', 'The White Oak', 'Belgia', 'be', null, 50.948812, 4.603209, 'https://thewhiteoak.be/'),
  (74, 'fort-resort-beemster', 'Fort Resort Beemster', 'Holandia', 'nl', null, 52.527916, 4.928467, 'https://www.fortresortbeemster.nl/?utm_source=Organic&utm_medium=SERP&utm_id=GBP'),
  (75, 'thermae-2000', 'Thermae 2000', 'Holandia', 'nl', null, 50.859997, 5.8238, 'http://www.thermae.nl/'),
  (76, 'thermen-bussloo-wellness-hotel', 'Thermen Bussloo Wellness & Hotel', 'Holandia', 'nl', null, 52.375205, 6.253518, 'http://www.thermenbussloo.nl/'),
  (77, 'beauty-sauna-peize', 'Beauty Sauna Peize', 'Holandia', 'nl', null, 53.144488, 6.484239, 'http://www.spawell.nl/'),
  (78, 'wellness-resort-elysium', 'Wellness Resort ELYSIUM', 'Holandia', 'nl', null, 51.994323, 4.543316, 'http://www.elysium.nl/'),
  (79, 'thermen-soesterberg', 'Thermen Soesterberg', 'Holandia', 'nl', null, 52.121436, 5.298855, 'https://www.thermensoesterberg.nl/'),
  (80, 'thermen-maastricht', 'Thermen Maastricht', 'Holandia', 'nl', null, 50.854304, 5.647295, 'https://www.thermenmaastricht.nl/'),
  (81, 'thermen-bad-nieuweschans', 'Thermen Bad Nieuweschans', 'Niemcy', 'de', null, 53.17958, 7.20365, 'http://www.thermenbadnieuweschans.nl/'),
  (82, 'thermen-maarssen', 'Thermen Maarssen', 'Holandia', 'nl', null, 52.146355, 5.083096, 'https://www.thermenmaarssen.nl/'),
  (83, 'spa-thermen-ridderrode', 'Spa Thermen Ridderrode', 'Holandia', 'nl', null, 52.425652, 4.620399, 'https://www.saunaridderrode.nl/'),
  (84, 'sauna-thermen-zuidwolde-bv', 'Sauna Thermen Zuidwolde BV', 'Holandia', 'nl', null, 52.646912, 6.430201, 'https://www.sauna-zuidwolde.nl/'),
  (85, 'thermes-de-spa', 'Thermes de Spa', 'Belgia', 'be', null, 50.494281, 5.864062, 'http://www.thermesdespa.com/'),
  (86, 'waer-waters', 'Waer Waters', 'Belgia', 'be', null, 50.876133, 4.2445, 'https://www.waerwaters.com/'),
  (87, 'thermen-katara', 'Thermen Katara', 'Belgia', 'be', null, 51.143534, 4.091613, 'https://www.katara.be/'),
  (88, 'elaisa-energetic-wellness', 'Elaisa Energetic Wellness', 'Belgia', 'be', null, 51.001723, 5.682439, 'https://www.elaisawellness.com/'),
  (89, 'thermen-berendonck-wellness-hotel', 'Thermen Berendonck - Wellness & Hotel', 'Holandia', 'nl', null, 51.808498, 5.780089, 'http://www.thermenberendonck.nl/'),
  (90, 'alpentherme-gastein', 'Alpentherme Gastein', 'Austria', 'at', null, 47.169762, 13.104415, 'https://www.alpentherme.com/'),
  (91, '4s-hotel-spa-resort-geinberg', '4S Hotel Spa Resort Geinberg', 'Austria', 'at', null, 48.263259, 13.298215, 'https://www.sparesortgeinberg.at/de/hotel/angebote'),
  (92, 'aqua-dome', 'Aqua Dome', 'Austria', 'at', null, 47.069668, 10.964717, 'https://www.aqua-dome.at/#gbp'),
  (93, 'tamina-therme', 'Tamina Therme', 'Szwajcaria', 'ch', null, 46.999349, 9.504329, 'https://www.taminatherme.ch/wellness-erlebnis'),
  (94, 'silvretta-therme-ischgl', 'Silvretta Therme Ischgl', 'Austria', 'at', null, 47.013269, 10.288815, 'http://www.silvrettatherme.at/'),
  (95, 'mineralbad-spa-rigi-kaltbad', 'Mineralbad & Spa Rigi Kaltbad', 'Szwajcaria', 'ch', null, 47.043713, 8.466102, 'https://www.aqua-spa-resorts.ch/de/mineralbad-spa-rigi-kaltbad'),
  (96, 'hurlimannbad-spa', 'Hürlimannbad & Spa', 'Szwajcaria', 'ch', null, 47.364942, 8.525115, 'https://www.aqua-spa-resorts.ch/de/huerlimannbad-spa-zuerich'),
  (97, 'therme-zurzach', 'Therme Zurzach', 'Szwajcaria', 'ch', null, 47.58922, 8.290646, 'http://www.thermezurzach.ch/'),
  (98, 'thermal-spa-loipersdorf', 'Thermal Spa Loipersdorf', 'Austria', 'at', null, 46.984825, 16.110814, 'https://www.therme.at/?utm_source=google&utm_medium=organic&utm_campaign=business-eintrag'),
  (99, 'aquardens', 'Aquardens', 'Włochy', 'it', null, 45.505999, 10.826955, 'http://www.aquardens.it/'),
  (100, 'aquagranda-active-you', 'Aquagranda Active You', 'Włochy', 'it', null, 46.554866, 10.144203, 'http://www.aquagrandalivigno.com/'),
  (101, 'cron4-hallenbad-sauna-bruneck', 'CRON4 Hallenbad & Sauna Bruneck', 'Włochy', 'it', null, 46.779453, 11.937196, 'http://www.cron4.it/'),
  (102, 'asmana-wellness-world-firenze', 'Asmana Wellness World Firenze', 'Włochy', 'it', null, 43.831328, 11.148899, 'https://www.asmana.it/'),
  (103, 'hotel-winkler-sport-spa-resort', 'Hotel Winkler | Sport & Spa Resort', 'Włochy', 'it', null, 46.769952, 11.922206, 'http://www.winklerhotels.com/'),
  (104, 'farris-bad', 'Farris Bad', 'Norwegia', 'no', null, 59.049461, 10.020538, 'https://farrisbad.no/?utm_campaign=gmb_hp&utm_medium=organic&utm_source=googlemybusiness'),
  (105, 'loyly-helsinki', 'Löyly Helsinki', 'Finlandia', 'fi', null, 60.152066, 24.930274, 'http://www.loylyhelsinki.fi/'),
  (106, 'therme-bucharest', 'Therme Bucharest', 'Rumunia', 'ro', null, 44.605123, 26.085435, 'https://www.therme.ro/'),
  (107, 'laznia-termalna-rudas', 'Łaźnia termalna Rudas', 'Węgry', 'hu', null, 47.489092, 19.047836, 'http://www.rudasfurdo.hu/')
on conflict (id) do nothing;
-- Obiekty robocze (8) — obecne w wydarzeniach/turniejach, ale nie na mapie.
-- DO WERYFIKACJI: po sprawdzeniu ustawić status='published' i uzupełnić współrzędne.
insert into public.venues (id, slug, name, country, country_code, city, status) values
  (108, 'thermaalbad', 'Thermaalbad', 'Holandia', 'nl', 'Eindhoven', 'draft'),
  (109, 'centrum-spa', 'Centrum SPA', 'Polska', 'pl', 'Słupsk', 'draft'),
  (110, 'termy-cieplickie', 'Termy Cieplickie', 'Polska', 'pl', 'Jelenia Góra', 'draft'),
  (111, 'liquidrom', 'Liquidrom', 'Niemcy', 'de', 'Berlin', 'draft'),
  (112, 'saunia-praha', 'Saunia Praha', 'Czechy', 'cz', 'Praga', 'draft'),
  (113, 'qc-terme', 'QC Terme', 'Włochy', 'it', 'Mediolan', 'draft'),
  (114, 'therme-wien', 'Therme Wien', 'Austria', 'at', 'Wiedeń', 'draft'),
  (115, 'bernaqua', 'Bernaqua', 'Szwajcaria', 'ch', 'Berno', 'draft')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.venues','id'), (select max(id) from public.venues));

-- Saunamistrzowie (9) — byt, którego prototyp nie miał
insert into public.saunamasters (id, slug, name, country, country_code, rank, is_trainer, is_judge) values
  (1, 'maciej-piczura', 'Maciej Piczura', 'Polska', 'pl', 'Pro Master', true, false),
  (2, 'robert-zidek', 'Robert Zídek', 'Czechy', 'cz', 'Pro Master', false, true),
  (3, 'arek-dan', 'Arek Dan', 'Polska', 'pl', 'Steam Expert', true, false),
  (4, 'jeremi-dygas', 'Jeremi Dygas', 'Polska', 'pl', 'Steam Expert', false, false),
  (5, 'lukas-weber', 'Lukas Weber', 'Niemcy', 'de', 'Pro Master', true, false),
  (6, 'sanne-de-vries', 'Sanne de Vries', 'Holandia', 'nl', 'Advanced', false, true),
  (7, 'petra-novakova', 'Petra Nováková', 'Czechy', 'cz', 'Advanced', false, false),
  (8, 'tomasz-kowal', 'Tomasz Kowal', 'Polska', 'pl', 'Advanced', false, true),
  (9, 'david-zatocil', 'David Zatočil', 'Czechy', 'cz', 'Steam Expert', false, false)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.saunamasters','id'), (select max(id) from public.saunamasters));

-- Saunamistrz ↔ obiekty (wiele obiektów, dokładnie jeden macierzysty)
insert into public.saunamaster_venues (saunamaster_id, venue_id, is_home, role) values
  (1, 13, false, 'zawodnik'),
  (1, 14, true, 'rezydent'),
  (2, 13, false, 'zawodnik'),
  (2, 55, true, 'zawodnik'),
  (2, 112, false, 'sędzia'),
  (3, 13, false, 'zawodnik'),
  (3, 109, false, 'zawodnik'),
  (3, 110, false, 'prowadzący'),
  (3, 55, true, 'rezydent'),
  (3, 20, false, 'gość'),
  (4, 13, false, 'zawodnik'),
  (4, 108, false, 'zawodnik'),
  (4, 109, true, 'rezydent'),
  (5, 108, false, 'zawodnik'),
  (5, 111, true, 'rezydent'),
  (6, 108, true, 'sędzia'),
  (7, 55, false, 'zawodniczka'),
  (7, 112, true, 'zawodniczka'),
  (8, 109, false, 'sędzia'),
  (8, 20, true, 'rezydent'),
  (9, 55, true, 'gość')
on conflict do nothing;

-- Wydarzenia (25)
insert into public.events (id, slug, title, type, scope, starts_on, ends_on, venue_id, ranking_points) values
  (1, 'the-battle-of-gladiators-mistrzostwa-swiata-1', 'The Battle of Gladiators — Mistrzostwa Świata', 'turniej', 'miedzynarodowe', '2026-03-06', '2026-03-09', 13, 100),
  (2, 'mistrzostwa-swiata-aufguss-eindhoven-2', 'Mistrzostwa Świata Aufguss — Eindhoven', 'turniej', 'miedzynarodowe', '2026-03-15', '2026-03-17', 108, 120),
  (3, 'aufguss-wm-open-runda-kwalifikacyjna-3', 'Aufguss-WM Open — runda kwalifikacyjna', 'turniej', 'miedzynarodowe', '2026-03-28', '2026-03-29', 55, 90),
  (4, 'mistrzostwa-polski-pts-classic-4', 'Mistrzostwa Polski PTS Classic', 'turniej', 'krajowe', '2026-03-21', '2026-03-22', 109, 60),
  (5, 'szkolenie-aufguss-poziom-podstawowy-5', 'Szkolenie Aufguss — poziom podstawowy', 'szkolenie', 'krajowe', '2026-03-24', '2026-03-26', 110, 0),
  (6, 'deutsche-aufguss-meisterschaft-6', 'Deutsche Aufguss Meisterschaft', 'turniej', 'krajowe', '2026-03-13', '2026-03-14', 111, 55),
  (7, 'mistrzostwa-czech-aufguss-7', 'Mistrzostwa Czech Aufguss', 'turniej', 'krajowe', '2026-03-20', '2026-03-21', 112, 55),
  (8, 'ceremonie-aufguss-dzien-powszedni-8', 'Ceremonie aufguss — dzień powszedni', 'ceremonia', 'lokalne', '2026-03-03', '2026-03-03', 55, 0),
  (9, 'noc-aufguss-z-goscmi-specjalnymi-9', 'Noc aufguss z gośćmi specjalnymi', 'noc-aufguss', 'lokalne', '2026-03-14', '2026-03-14', 55, 0),
  (10, 'ceremonie-aufguss-weekend-10', 'Ceremonie aufguss — weekend', 'ceremonia', 'lokalne', '2026-03-21', '2026-03-21', 55, 0),
  (11, 'ceremonia-aufguss-poranek-saunowy-11', 'Ceremonia aufguss — poranek saunowy', 'ceremonia', 'lokalne', '2026-03-11', '2026-03-11', 111, 0),
  (12, 'nocna-ceremonia-aufguss-12', 'Nocna ceremonia Aufguss', 'noc-aufguss', 'lokalne', '2026-03-29', '2026-03-29', 111, 0),
  (13, 'dyzur-saunamistrza-ceremonie-dzienne-13', 'Dyżur saunamistrza — ceremonie dzienne', 'ceremonia', 'lokalne', '2026-03-05', '2026-03-05', 109, 0),
  (14, 'noc-aufguss-edycja-wiosenna-14', 'Noc aufguss — edycja wiosenna', 'noc-aufguss', 'lokalne', '2026-03-19', '2026-03-19', 109, 0),
  (15, 'ceremonie-aufguss-dzien-tematyczny-15', 'Ceremonie aufguss — dzień tematyczny', 'ceremonia', 'lokalne', '2026-03-07', '2026-03-07', 20, 0),
  (16, 'noc-aufguss-xxl-16', 'Noc aufguss XXL', 'noc-aufguss', 'lokalne', '2026-03-28', '2026-03-28', 20, 0),
  (17, 'ceremonie-aufguss-wieczor-17', 'Ceremonie aufguss — wieczór', 'ceremonia', 'lokalne', '2026-03-12', '2026-03-12', 112, 0),
  (18, 'dyzur-saunamistrza-ceremonie-autorskie-18', 'Dyżur saunamistrza — ceremonie autorskie', 'ceremonia', 'lokalne', '2026-03-10', '2026-03-10', 14, 0),
  (19, 'noc-aufguss-show-pod-tatrami-19', 'Noc aufguss — Show pod Tatrami', 'noc-aufguss', 'lokalne', '2026-03-18', '2026-03-18', 14, 0),
  (20, 'szkolenie-aufguss-warsztaty-z-mistrzem-swiata-20', 'Szkolenie Aufguss — warsztaty z Mistrzem Świata', 'szkolenie', 'krajowe', '2026-03-31', '2026-04-02', 14, 0),
  (21, 'sobotnie-ceremonie-aufguss-21', 'Sobotnie ceremonie aufguss', 'ceremonia', 'lokalne', '2026-03-21', '2026-03-21', 111, 0),
  (22, 'wieczor-saun-parowych-22', 'Wieczór saun parowych', 'ceremonia', 'lokalne', '2026-03-21', '2026-03-21', 109, 0),
  (23, 'noc-aufguss-edycja-dj-23', 'Noc aufguss — edycja DJ', 'noc-aufguss', 'lokalne', '2026-03-21', '2026-03-21', 20, 0),
  (24, 'aufguss-wieczorny-aromaty-lasu-24', 'Aufguss wieczorny — aromaty lasu', 'ceremonia', 'lokalne', '2026-03-21', '2026-03-21', 112, 0),
  (25, 'show-pod-tatrami-sobota-25', 'Show pod Tatrami — sobota', 'noc-aufguss', 'lokalne', '2026-03-21', '2026-03-21', 14, 0)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.events','id'), (select max(id) from public.events));

-- Obsada wydarzeń
insert into public.event_masters (event_id, saunamaster_id, role) values
  (1, 1, 'zawodnik'),
  (1, 2, 'zawodnik'),
  (1, 3, 'zawodnik'),
  (1, 4, 'zawodnik'),
  (2, 5, 'zawodnik'),
  (2, 6, 'sędzia'),
  (2, 4, 'zawodnik'),
  (3, 2, 'zawodnik'),
  (3, 7, 'zawodniczka'),
  (4, 3, 'zawodnik'),
  (4, 4, 'zawodnik'),
  (4, 8, 'sędzia'),
  (5, 3, 'prowadzący'),
  (6, 5, 'zawodnik'),
  (7, 7, 'zawodniczka'),
  (7, 2, 'sędzia'),
  (8, 3, 'rezydent'),
  (9, 2, 'gość'),
  (9, 9, 'gość'),
  (10, 3, 'rezydent'),
  (11, 5, 'rezydent'),
  (12, 5, 'rezydent'),
  (13, 4, 'rezydent'),
  (14, 4, 'rezydent'),
  (14, 8, 'gość'),
  (15, 8, 'rezydent'),
  (16, 8, 'rezydent'),
  (16, 3, 'gość'),
  (17, 7, 'rezydentka'),
  (18, 1, 'rezydent'),
  (19, 1, 'rezydent'),
  (20, 1, 'prowadzący'),
  (21, 5, 'rezydent'),
  (22, 4, 'rezydent'),
  (23, 8, 'rezydent'),
  (23, 3, 'gość'),
  (24, 7, 'rezydentka'),
  (25, 1, 'rezydent')
on conflict do nothing;

-- Turnieje (9)
insert into public.tournaments (id, slug, name, scope, organizer, season, tagline, host_venue_id) values
  (1, 'battle-of-gladiators', 'The Battle of Gladiators', 'miedzynarodowe', 'WCF · Mistrzostwa Świata Aufguss', '2026', 'Najbardziej prestiżowy turniej aufguss na świecie — od eliminacji krajowych po wielki finał w Colosseum Sauna Arena w Czeladzi.', 13),
  (2, 'aufguss-wm', 'Aufguss WM', 'miedzynarodowe', 'Aufguss WM · Mistrzostwa Świata', '2026', 'Klasyczne mistrzostwa świata w konkurencjach Freestyle i Modern Classic.', 76),
  (3, 'mp-pts-classic', 'Mistrzostwa Polski PTS Classic', 'krajowe', 'PTS · Mistrzostwa Polski', '2026', 'Krajowe mistrzostwa saunamistrzów — droga na arenę międzynarodową.', 109),
  (4, 'deutsche-meisterschaft', 'Deutsche Aufguss Meisterschaft', 'krajowe', 'Mistrzostwa Niemiec', '2026', 'Krajowe mistrzostwa Niemiec — najsilniejsza scena aufguss w Europie.', 111),
  (5, 'mistrzostwa-czech', 'Mistrzostwa Czech Aufguss', 'krajowe', 'Mistrzostwa Czech', '2026', 'Krajowe mistrzostwa Czech.', 112),
  (6, 'puchar-polski-aufguss', 'Puchar Polski Aufguss', 'krajowe', 'PTS · Puchar Polski', '2026', 'Cykl pucharowy z rundami w największych polskich obiektach.', 20),
  (7, 'nocne-mistrzostwa-slaska', 'Nocne Mistrzostwa Śląska', 'krajowe', 'Turniej regionalny', '2026', 'Regionalny turniej nocnych ceremonii aufguss na Śląsku.', 13),
  (8, 'aufguss-cup-sued', 'Aufguss Cup Süd', 'krajowe', 'Turniej regionalny', '2026', 'Południowoniemiecki turniej aufguss.', 50),
  (9, 'dutch-aufguss-open', 'Dutch Aufguss Open', 'krajowe', 'Mistrzostwa Holandii', '2026', 'Otwarte mistrzostwa Holandii.', 108)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.tournaments','id'), (select max(id) from public.tournaments));

-- Etapy turniejów
insert into public.tournament_stages (id, tournament_id, position, label, description) values
  (1, 1, 0, 'Eliminacje krajowe', 'Siedem krajów wyłania reprezentantów w obiektach na swoim terenie.'),
  (2, 1, 1, 'Finały krajowe', 'Zwycięzcy eliminacji walczą o tytuł mistrza kraju i awans na Mistrzostwa Świata.'),
  (3, 1, 2, 'Mistrzostwa Świata', 'Wielki finał — reprezentanci wszystkich krajów w Colosseum Sauna Arena.'),
  (4, 2, 0, 'Eliminacje międzynarodowe', 'Runda kwalifikacyjna w wybranych obiektach.'),
  (5, 2, 1, 'Finał', 'Wielki finał w Thermen Bussloo.'),
  (6, 3, 0, 'Eliminacje regionalne', 'Turnieje kwalifikacyjne w regionach.'),
  (7, 3, 1, 'Finał krajowy', 'Wielki finał Mistrzostw Polski.'),
  (8, 4, 0, 'Finał krajowy', 'Mistrzostwa Niemiec.'),
  (9, 5, 0, 'Finał krajowy', 'Mistrzostwa Czech.'),
  (10, 6, 0, 'Rundy pucharowe', 'Kolejne rundy w różnych obiektach.'),
  (11, 6, 1, 'Finał', 'Wielki finał Pucharu Polski.'),
  (12, 7, 0, 'Finał', 'Nocny finał w Colosseum Sauna Arena.'),
  (13, 8, 0, 'Finał', 'Finał regionu.'),
  (14, 9, 0, 'Finał krajowy', 'Mistrzostwa Holandii.')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.tournament_stages','id'), (select max(id) from public.tournament_stages));

-- Zgłoszenia w etapach
insert into public.tournament_entries (stage_id, venue_id, venue_name, city, country, country_code, starts_on, ends_on, highlight) values
  (1, 20, 'Suntago', 'Wręcza', 'Polska', 'pl', '2026-01-17', null, false),
  (1, 13, 'Termy Rzymskie', 'Czeladź', 'Polska', 'pl', '2026-01-24', null, false),
  (1, 55, 'Satama Sauna Resort', 'Wendisch-Rietz', 'Niemcy', 'de', '2026-01-31', null, false),
  (1, 112, 'Saunia Praha', 'Praga', 'Czechy', 'cz', '2026-02-07', null, false),
  (1, 113, 'QC Terme', 'Mediolan', 'Włochy', 'it', '2026-02-14', null, false),
  (1, 108, 'Thermaalbad', 'Eindhoven', 'Holandia', 'nl', '2026-02-21', null, false),
  (1, 114, 'Therme Wien', 'Wiedeń', 'Austria', 'at', '2026-02-24', null, false),
  (1, 115, 'Bernaqua', 'Berno', 'Szwajcaria', 'ch', '2026-02-27', null, false),
  (2, 13, 'Termy Rzymskie', 'Czeladź', 'Polska', 'pl', '2026-03-01', null, false),
  (2, 55, 'Satama Sauna Resort', 'Wendisch-Rietz', 'Niemcy', 'de', '2026-03-02', null, false),
  (2, 112, 'Saunia Praha', 'Praga', 'Czechy', 'cz', '2026-03-03', null, false),
  (2, 108, 'Thermaalbad', 'Eindhoven', 'Holandia', 'nl', '2026-03-04', null, false),
  (3, 13, 'Termy Rzymskie', 'Czeladź', 'Polska', 'pl', '2026-03-06', '2026-03-09', true),
  (4, 55, 'Satama Sauna Resort', 'Wendisch-Rietz', 'Niemcy', 'de', '2026-03-28', '2026-03-29', false),
  (4, 108, 'Thermaalbad', 'Eindhoven', 'Holandia', 'nl', '2026-04-04', null, false),
  (5, 76, 'Thermen Bussloo', 'Voorst', 'Holandia', 'nl', '2026-04-18', '2026-04-20', true),
  (6, 20, 'Suntago', 'Wręcza', 'Polska', 'pl', '2026-02-14', null, false),
  (6, 110, 'Termy Cieplickie', 'Jelenia Góra', 'Polska', 'pl', '2026-02-21', null, false),
  (6, 14, 'Chochołowskie Termy', 'Chochołów', 'Polska', 'pl', '2026-02-28', null, false),
  (7, 109, 'Centrum SPA', 'Słupsk', 'Polska', 'pl', '2026-03-21', '2026-03-22', true),
  (8, 111, 'Liquidrom', 'Berlin', 'Niemcy', 'de', '2026-03-13', '2026-03-14', true),
  (9, 112, 'Saunia Praha', 'Praga', 'Czechy', 'cz', '2026-03-20', '2026-03-21', true),
  (10, 20, 'Suntago', 'Wręcza', 'Polska', 'pl', '2026-04-11', null, false),
  (10, 13, 'Termy Rzymskie', 'Czeladź', 'Polska', 'pl', '2026-04-25', null, false),
  (10, 14, 'Chochołowskie Termy', 'Chochołów', 'Polska', 'pl', '2026-05-09', null, false),
  (11, 20, 'Suntago', 'Wręcza', 'Polska', 'pl', '2026-05-23', null, true),
  (12, 13, 'Termy Rzymskie', 'Czeladź', 'Polska', 'pl', '2026-04-18', null, true),
  (13, 50, 'Therme Erding', 'Erding', 'Niemcy', 'de', '2026-03-28', null, true),
  (14, 108, 'Thermaalbad', 'Eindhoven', 'Holandia', 'nl', '2026-04-04', '2026-04-05', true);

-- Archiwum wyników (podium)
insert into public.tournament_results (tournament_id, year, city, place, saunamaster_id, name, country, country_code, points) values
  (1, 2025, 'Czeladź', 1, 2, 'Robert Zídek', 'Czechy', 'cz', 284),
  (1, 2025, 'Czeladź', 2, 1, 'Maciej Piczura', 'Polska', 'pl', 279),
  (1, 2025, 'Czeladź', 3, 5, 'Lukas Weber', 'Niemcy', 'de', 271),
  (1, 2024, 'Czeladź', 1, 1, 'Maciej Piczura', 'Polska', 'pl', 288),
  (1, 2024, 'Czeladź', 2, 2, 'Robert Zídek', 'Czechy', 'cz', 282),
  (1, 2024, 'Czeladź', 3, 3, 'Arek Dan', 'Polska', 'pl', 270),
  (1, 2023, 'Czeladź', 1, 1, 'Maciej Piczura', 'Polska', 'pl', 281),
  (1, 2023, 'Czeladź', 2, 9, 'David Zatočil', 'Czechy', 'cz', 276),
  (1, 2023, 'Czeladź', 3, 4, 'Jeremi Dygas', 'Polska', 'pl', 268),
  (3, 2025, 'Słupsk', 1, 3, 'Arek Dan', 'Polska', 'pl', 262),
  (3, 2025, 'Słupsk', 2, 4, 'Jeremi Dygas', 'Polska', 'pl', 258),
  (3, 2025, 'Słupsk', 3, 8, 'Tomasz Kowal', 'Polska', 'pl', 249),
  (3, 2024, 'Wręcza', 1, 1, 'Maciej Piczura', 'Polska', 'pl', 270),
  (3, 2024, 'Wręcza', 2, 3, 'Arek Dan', 'Polska', 'pl', 264),
  (3, 2024, 'Wręcza', 3, 4, 'Jeremi Dygas', 'Polska', 'pl', 255)
on conflict do nothing;

-- Wpisy (19) — body jako dokument ProseMirror
insert into public.posts (slug, category, cover, title, lead, body, score, venue_id, status, published_at) values
  ('satama-recenzja', 'Recenzja', 'pc1', 'Rzymski przepych, który działa nie tylko na Instagramie', 'Colosseum Sauna Arena robi wrażenie skalą, ale prawdziwą wartością są ceremonie i obsługa.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Satama to obiekt, który łatwo sprowadzić do efektownych zdjęć — antyczne kolumny, ogromna arena, para unosząca się pod sklepieniem. Byłoby jednak krzywdzące zatrzymać się na warstwie wizualnej."}]},{"type":"paragraph","content":[{"type":"text","text":"Program ceremonii jest gęsty i różnorodny, a saunamistrzowie prowadzą seans jak spektakl — z narracją, muzyką i wyczuciem temperatury. Strefa banii i rytuał z wenikiem to mocne punkty. Widać, że obiekt traktuje aufguss jako sztukę, nie dodatek do basenu."}]},{"type":"paragraph","content":[{"type":"text","text":"Kontekst też robi swoje: jezioro Scharmützelsee tuż obok sprawia, że schłodzenie po saunie staje się osobnym przeżyciem. Latem to jeden z najlepszych powodów, by tu przyjechać."}]},{"type":"paragraph","content":[{"type":"text","text":"Minusy? W szczycie weekendu bywa tłoczno, a część seansów wymaga wcześniejszej rezerwacji. Mimo to — jeden z najlepszych obiektów aufguss w Europie, do którego chce się wracać."}]}]}'::jsonb, 8.8, 55, 'published', now()),
  ('liquidrom-recenzja', 'Recenzja', 'pc2', 'Berliński minimalizm pod wodą', 'Kultowa architektura i podwodna muzyka, ale program aufguss bywa nierówny.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Liquidrom to instytucja — basen solankowy pod betonową kopułą z muzyką słyszalną pod wodą robi wrażenie za każdym razem. To miejsce, które w Berlinie stało się synonimem miejskiego relaksu."}]},{"type":"paragraph","content":[{"type":"text","text":"Aufguss? Wieczorami potrafi być znakomity, prowadzony z wyczuciem i pomysłem. W ciągu dnia poziom bywa jednak nierówny — czasem to raczej rutynowy seans niż ceremonia."}]},{"type":"paragraph","content":[{"type":"text","text":"To miejsce bardziej o atmosferze i wyciszeniu niż o ceremonialnym show. Jeśli szukasz spokoju w centrum miasta — trafisz idealnie. Jeśli wielkiego widowiska — bywa różnie."}]}]}'::jsonb, 7.9, 111, 'published', now()),
  ('termy-rzymskie-recenzja', 'Recenzja', 'pc3', 'Arena, która podniosła poprzeczkę całej Europie', 'Najlepszy program ceremonii w Polsce i sceneria, która robi robotę nawet przy pustej widowni.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Są obiekty, które budują wrażenie scenografią, i takie, które budują je poziomem seansów. Termy Rzymskie należą do rzadkiej grupy, w której obie te rzeczy grają na jedną nutę. Rzymska stylistyka mogłaby łatwo osunąć się w kicz, a jednak trzyma proporcje i pracuje na atmosferę zamiast ją przykrywać."}]},{"type":"paragraph","content":[{"type":"text","text":"Najważniejsze dzieje się jednak w grafiku. Program ceremonii jest gęsty, prowadzony przez saunamistrzów z międzynarodowym doświadczeniem, a różnica między seansem porannym a wieczornym jest tu kwestią repertuaru, nie jakości. To rzadkość — w większości dużych obiektów popołudnie bywa najsłabszą częścią dnia."}]},{"type":"paragraph","content":[{"type":"text","text":"Osobny rozdział to wielkie wydarzenia. Obiekt potrafi obsłużyć turniejową publiczność bez rozsypania codziennego harmonogramu, co przy tej skali jest osiągnięciem organizacyjnym samym w sobie."}]},{"type":"paragraph","content":[{"type":"text","text":"Zastrzeżenie mam jedno, za to realne: w weekendy popularność potrafi przełożyć się na kolejki do najbardziej obleganych seansów. Warto planować wizytę w tygodniu — wtedy to po prostu najlepszy adres aufguss w kraju."}]}]}'::jsonb, 9.2, 13, 'published', now()),
  ('loyly-recenzja', 'Recenzja', 'pc4', 'Fińska szczerość, czyli sauna bez scenografii', 'Żadnych efektów specjalnych — drewno, ogień i Bałtyk kilka kroków dalej.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Löyly Helsinki jest przeciwieństwem wszystkiego, co zwykle chwalę w wielkich obiektach aufguss. Nie ma tu areny, choreografii ani muzyki budującej napięcie. Jest drewno, dym, gorąco i morze, do którego schodzi się po schodkach prosto z tarasu."}]},{"type":"paragraph","content":[{"type":"text","text":"I właśnie dlatego to miejsce trafia na tak wysokie miejsce. Fińska szkoła traktuje saunę jako codzienność, nie jako spektakl — a poziom rzemiosła, czyli jakość pary i praca z piecem, jest tu wzorcowy. Sauna dymna to doświadczenie, którego nie zastąpi żaden program ceremonii."}]},{"type":"paragraph","content":[{"type":"text","text":"Architektura zasługuje na osobne zdanie: drewniany, falujący budynek nad zatoką jest publicznie dostępny także dla osób, które przyszły tylko na kawę. To rzadki przykład obiektu wpisanego w miasto, a nie odgrodzonego od niego."}]},{"type":"paragraph","content":[{"type":"text","text":"Dla kogo to nie będzie? Dla szukających klasycznego aufguss z ręcznikiem i show. Tego tu po prostu nie ma i nie ma być."}]}]}'::jsonb, 9, 105, 'published', now()),
  ('chocholowskie-recenzja', 'Recenzja', 'pc1', 'Tatry za oknem i seanse, które trzymają równy poziom', 'Przewidywalnie dobry program i widok, który sam w sobie jest połową wrażenia.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Chochołowskie Termy mają atut nie do skopiowania: panoramę Tatr z saun i stref wypoczynku. Brzmi jak dodatek marketingowy, ale realnie zmienia odbiór seansu — schłodzenie z takim widokiem zostaje w pamięci dłużej niż niejeden efektowny aufguss."}]},{"type":"paragraph","content":[{"type":"text","text":"Program ceremonii jest solidny i, co ważniejsze, powtarzalny. Nie trafiłem tu jeszcze na seans słaby, choć nie trafiłem też na taki, który by mnie całkowicie zaskoczył. To obiekt równy, dobrze prowadzony, z saunamistrzami rozumiejącymi, że publiczność górska bywa inna niż wielkomiejska."}]},{"type":"paragraph","content":[{"type":"text","text":"Strefa saun jest przemyślana, a rytuały autorskie coraz odważniejsze — widać, że obiekt inwestuje w ludzi, nie tylko w infrastrukturę."}]},{"type":"paragraph","content":[{"type":"text","text":"Minus? Sezonowość. W szczycie ferii i długich weekendów tłok potrafi zjeść sporo z tego spokoju, za który się tu przyjeżdża."}]}]}'::jsonb, 8.6, 14, 'published', now()),
  ('vabali-recenzja', 'Recenzja', 'pc2', 'Balijska sceneria w środku Berlina', 'Ogromny wybór saun i konsekwentnie utrzymany klimat, choć aufguss bywa zachowawczy.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Vabali to popis budowania nastroju. Drewno, woda, zieleń i architektura inspirowana Bali sprawiają, że po kilkunastu minutach zapomina się, że za płotem jest wielkie miasto. Konsekwencja tej scenografii robi w Berlinie różnicę."}]},{"type":"paragraph","content":[{"type":"text","text":"Wybór saun jest imponujący i dobrze rozłożony — od łagodnych po naprawdę mocne, z sensownymi strefami ciszy pomiędzy. Obsługa pilnuje reguł, dzięki czemu spokój nie jest tu deklaracją, tylko stanem faktycznym."}]},{"type":"paragraph","content":[{"type":"text","text":"Aufguss stoi na przyzwoitym, wyrównanym poziomie, ale rzadko wychodzi poza sprawdzony schemat. To ceremonie poprawne i przyjemne, tylko niekoniecznie takie, o których opowiada się potem znajomym."}]},{"type":"paragraph","content":[{"type":"text","text":"Jeśli szukasz całodniowego wyciszenia w wysokim standardzie — trafiłeś idealnie. Jeśli mistrzowskiego show — celuj gdzie indziej."}]}]}'::jsonb, 8.5, 61, 'published', now()),
  ('bussloo-recenzja', 'Recenzja', 'pc3', 'Holenderska szkoła ceremonii w kameralnym wydaniu', 'Świetna strefa zewnętrzna i aufguss prowadzony z wyczuciem, bez przesadnego rozmachu.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Holandia od lat gra w aufguss w pierwszej lidze i Thermen Bussloo dobrze tłumaczy dlaczego. Ceremonie prowadzone są tu z wyczuciem tempa i temperatury, a saunamistrzowie potrafią pracować z publicznością zamiast po prostu odrobić program."}]},{"type":"paragraph","content":[{"type":"text","text":"Duży plus za strefę zewnętrzną — sauny wtopione w zieleń i przestrzeń do schłodzenia, która nie sprowadza się do jednego zimnego prysznica. To właśnie tam obiekt jest najlepszy."}]},{"type":"paragraph","content":[{"type":"text","text":"Skala jest średnia i to działa na korzyść: kameralność sprzyja kontaktowi między prowadzącym a gośćmi, czego w wielkich arenach często brakuje."}]},{"type":"paragraph","content":[{"type":"text","text":"Cena za wstęp należy do wyższych w regionie, a dla gościa z zagranicy dochodzi bariera językowa przy części seansów tematycznych. Warto o tym wiedzieć przed wizytą."}]}]}'::jsonb, 8.4, 76, 'published', now()),
  ('suntago-recenzja', 'Recenzja', 'pc4', 'Skala, która wreszcie pracuje na jakość', 'Największy obiekt w regionie coraz poważniej traktuje sauny — i widać to w programie.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Suntago długo kojarzyło się przede wszystkim z częścią wodną i rodzinną rozrywką. Strefa saunowa przez ten cień się przebijała, ale ostatnie sezony wyraźnie zmieniły proporcje: program ceremonii jest dziś obszerny, a saunamistrzowie mają wyraźnie więcej do powiedzenia."}]},{"type":"paragraph","content":[{"type":"text","text":"Wielkość obiektu przestała być wadą. Sauny tematyczne trzymają poziom, strefa dla dorosłych jest realnie oddzielona, a rozmach pozwala na seanse dla dużej widowni bez ścisku w kabinie."}]},{"type":"paragraph","content":[{"type":"text","text":"To wciąż nie jest miejsce na kameralne wyciszenie — do Suntago przyjeżdża się po energię i różnorodność, nie po ciszę."}]},{"type":"paragraph","content":[{"type":"text","text":"Największe zastrzeżenie dotyczy godzin szczytu: w weekendy część atrakcji obsługiwana jest w tempie, które odbija się na spokoju seansu. W tygodniu obiekt wypada wyraźnie lepiej."}]}]}'::jsonb, 8.1, 20, 'published', now()),
  ('aquapalace-recenzja', 'Recenzja', 'pc1', 'Czeska szkoła aufguss w solidnym wydaniu', 'Mocna kadra saunamistrzów i porządny warsztat, choć obiekt bywa przytłoczony ruchem.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Czechy mają jedną z najmocniejszych scen aufguss w Europie i Aquapalace Praha regularnie tę tezę potwierdza. Warsztat prowadzących jest tu wysoki: praca ręcznikiem czysta, dobór aromatów przemyślany, tempo seansu budowane świadomie."}]},{"type":"paragraph","content":[{"type":"text","text":"Strefa saunowa jest dobrze zaprojektowana, z sensownym rozkładem temperatur i miejscem na odpoczynek między ceremoniami. Widać szkołę, w której technika liczy się bardziej niż efekt."}]},{"type":"paragraph","content":[{"type":"text","text":"Obiekt pełni jednak podwójną rolę — dużego aquaparku i poważnego adresu saunowego jednocześnie. To bywa odczuwalne, zwłaszcza w weekendy, gdy ruch w części wodnej przenika do strefy ciszy."}]},{"type":"paragraph","content":[{"type":"text","text":"Mimo to dla kogoś, kto chce zobaczyć czeski aufguss bez wyprawy w mniejsze miasta, to najprostszy i bardzo dobry wybór."}]}]}'::jsonb, 8, 32, 'published', now()),
  ('aqua-dome-recenzja', 'Recenzja', 'pc2', 'Alpejska panorama, która zmienia sens schłodzenia', 'Widok i termy w najwyższej lidze, program ceremonii już niekoniecznie.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aqua Dome sprzedaje przede wszystkim położenie i trudno mieć o to pretensję — alpejskie otoczenie sprawia, że wyjście z sauny na mróz staje się osobną atrakcją. Pod tym względem niewiele obiektów w Europie może się równać."}]},{"type":"paragraph","content":[{"type":"text","text":"Sama infrastruktura termalna jest znakomita: baseny, strefy relaksu i zaplecze utrzymane w standardzie, którego oczekuje się w tej cenie."}]},{"type":"paragraph","content":[{"type":"text","text":"Aufguss wypada jednak blado na tle otoczenia. Ceremonie są poprawne, ale rzadko wychodzą poza rutynę, a repertuar bywa powtarzalny. To obiekt termalny z saunami, nie obiekt saunowy z termami — i tę różnicę czuć w programie."}]},{"type":"paragraph","content":[{"type":"text","text":"Przyjeżdżaj dla gór i wody. Jeśli aufguss jest dla ciebie najważniejszy, potraktuj go tu jako miły dodatek, a nie powód wyjazdu."}]}]}'::jsonb, 7.8, 92, 'published', now()),
  ('thermae-2000-recenzja', 'Recenzja', 'pc3', 'Klasyk z Limburgii, który potrzebuje odświeżenia', 'Wciąż przyjemny i dobrze prowadzony, ale konkurencja przez ostatnie lata pojechała dalej.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Thermae 2000 przez lata było punktem odniesienia w Beneluksie i wciąż ma sporo z dawnej klasy: położenie na wzgórzu, panoramiczne widoki i spokojną, dojrzałą publiczność, która wie, po co przyszła."}]},{"type":"paragraph","content":[{"type":"text","text":"Ceremonie prowadzone są kompetentnie, bez fajerwerków, ale i bez wpadek. Strefa saun zachowuje przyjemny rytm dnia, a obsługa dba o reguły ciszy."}]},{"type":"paragraph","content":[{"type":"text","text":"Problem w tym, że obiekt zatrzymał się w miejscu, podczas gdy holenderska i niemiecka konkurencja wyraźnie przyspieszyła. Część infrastruktury nosi ślady lat, a program ceremonii nie ma dziś nic, czego nie znajdziesz bliżej i taniej."}]},{"type":"paragraph","content":[{"type":"text","text":"To nadal dobry adres na spokojny dzień — po prostu nie jest już tym, czym był dekadę temu."}]}]}'::jsonb, 7.6, 75, 'published', now()),
  ('termy-maltanskie-recenzja', 'Recenzja', 'pc4', 'Miejski kompromis z ambitną strefą saun', 'Wygodny miejski adres, ale aufguss walczy tu o uwagę z aquaparkiem.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Termy Maltańskie mają zaletę, której nie kupi się żadną inwestycją: są w mieście, łatwo dostępne i można tu wpaść po pracy. Dla lokalnej społeczności saunowej to realna wartość."}]},{"type":"paragraph","content":[{"type":"text","text":"Strefa saun jest większa i ambitniejsza, niż sugerowałby profil obiektu. Program ceremonii istnieje, jest prowadzony regularnie, a część saunamistrzów naprawdę stara się wyjść poza standard."}]},{"type":"paragraph","content":[{"type":"text","text":"Charakter obiektu robi jednak swoje. To przede wszystkim duży kompleks basenowy, w którym sauny są jedną ze stref, a nie sercem miejsca. Odbija się to na atmosferze — o ciszę bywa trudno, zwłaszcza popołudniami."}]},{"type":"paragraph","content":[{"type":"text","text":"Traktuję to miejsce jako solidny wybór miejski, nie jako cel wyprawy. W tej roli sprawdza się dobrze i nie ma powodu, by od niego stronić."}]}]}'::jsonb, 7.2, 9, 'published', now()),
  ('polska-potega', 'Felieton', 'pc4', 'Dlaczego Polska stała się saunową potęgą Europy', 'W pięć lat przeszliśmy drogę, którą inne kraje pokonywały dekadę.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Jeszcze niedawno aufguss w Polsce był niszą dla wtajemniczonych. Dziś mamy własne mistrzostwa, obiekty inwestujące w saunamistrzów i publiczność, która rozumie ceremonię i potrafi ją docenić."}]},{"type":"paragraph","content":[{"type":"text","text":"Zadecydowało kilka rzeczy naraz: fala nowych, ambitnych obiektów termalnych, pokolenie saunamistrzów z międzynarodowymi sukcesami oraz społeczność, która zamieniła saunowanie w styl życia."}]},{"type":"paragraph","content":[{"type":"text","text":"Co może nas zatrzymać? Przede wszystkim ryzyko, że komercja wyprzedzi rzemiosło. Dopóki jednak w centrum pozostaje jakość ceremonii, kierunek jest znakomity."}]}]}'::jsonb, null, null, 'published', now()),
  ('pts-classic-zapisy', 'Turnieje', 'pc2', 'Ruszają zapisy na Mistrzostwa Polski PTS Classic 2026', 'Rejestracja zawodników otwarta do końca lipca. Wielki finał w Słupsku.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Zapraszamy saunamistrzów do rejestracji na tegoroczne Mistrzostwa Polski PTS Classic. Eliminacje regionalne ruszają jesienią, a wielki finał odbędzie się w Słupsku."}]},{"type":"paragraph","content":[{"type":"text","text":"W tym roku spodziewamy się rekordowej frekwencji — zarówno wśród doświadczonych zawodników, jak i debiutantów. Regulamin oraz formularz zgłoszeniowy dostępne są w panelu zawodnika."}]},{"type":"paragraph","content":[{"type":"text","text":"To najważniejszy krajowy turniej w kalendarzu, a dla wielu saunamistrzów przepustka na areny międzynarodowe."}]}]}'::jsonb, null, null, 'published', now()),
  ('pts-nowy-ranking', 'Społeczność', 'pc3', 'Rusza 10-stopniowy system rang saunamistrzów', 'Wspólnie z aufguss.world wdrażamy skalę rang liczoną z punktów za turnieje.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Od teraz osiągnięcia z turniejów przekładają się na rangę widoczną na profilu zawodnika — od Rookie aż po Pro Master. Punkty naliczane są automatycznie na podstawie wyników."}]},{"type":"paragraph","content":[{"type":"text","text":"System ma uporządkować scenę i dać obiektom oraz publiczności czytelny sygnał o poziomie saunamistrza."}]},{"type":"paragraph","content":[{"type":"text","text":"To ważny krok w profesjonalizacji polskiej i europejskiej sceny aufguss."}]}]}'::jsonb, null, null, 'published', now()),
  ('satama-noc-aufguss', 'Wydarzenie', 'pc2', 'Noc aufguss z Robertem Zídkiem i Davidem Zatočilem', 'Wyjątkowy wieczór z dwoma mistrzami świata — bilety w sprzedaży od piątku.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Zapraszamy na wyjątkową noc aufguss z udziałem dwóch mistrzów świata. Wieczór wypełnią autorskie ceremonie, muzyka na żywo i specjalne rytuały przygotowane wyłącznie na tę okazję."}]},{"type":"paragraph","content":[{"type":"text","text":"Liczba miejsc jest ograniczona, a bilety trafią do sprzedaży w piątek. Rekomendujemy wcześniejszą rezerwację — poprzednie edycje wyprzedały się w kilka godzin."}]}]}'::jsonb, null, null, 'published', now()),
  ('satama-nowa-sauna', 'Obiekt', 'pc3', 'Nowa sauna zewnętrzna nad Scharmützelsee', 'Oddajemy do użytku panoramiczną saunę z widokiem na jezioro.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Nowa sauna zewnętrzna z tarasem widokowym jest już otwarta dla gości. Schłodzenie w jeziorze Scharmützelsee macie teraz na wyciągnięcie ręki."}]},{"type":"paragraph","content":[{"type":"text","text":"To kolejny etap rozbudowy resortu — stawiamy na połączenie natury z najwyższą jakością ceremonii aufguss."}]}]}'::jsonb, null, null, 'published', now()),
  ('satama-letni-program', 'Ceremonie', 'pc1', 'Letni program ceremonii — nowe aromaty', 'Cedr, mięta i cytrusy w odświeżonym planie ceremonii na lato.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Wraz z latem odświeżamy plan ceremonii. Do stałego repertuaru dołączają nowe kompozycje zapachowe: cedr syberyjski, mięta pieprzowa oraz orzeźwiające cytrusy z imbirem."}]},{"type":"paragraph","content":[{"type":"text","text":"Nowy grafik ceremonii znajdziecie w kalendarzu obiektu. Zapraszamy na saunowe lato."}]}]}'::jsonb, null, null, 'published', now()),
  ('zidek-mistrz-swiata', 'Turnieje', 'pc4', 'Robert Zídek po raz trzeci Mistrzem Świata Aufguss', 'Czeski saunamistrz obronił tytuł podczas The Battle of Gladiators w Termach Rzymskich w Czeladzi.', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Robert Zídek po raz trzeci sięgnął po tytuł Mistrza Świata Aufguss. Finał The Battle of Gladiators rozegrano w Termach Rzymskich w Czeladzi, na słynnej Colosseum Arenie."}]},{"type":"paragraph","content":[{"type":"text","text":"Czeski saunamistrz pokonał silną, międzynarodową stawkę, prezentując dopracowany autorski program łączący choreografię, muzykę i perfekcyjną pracę parą."}]},{"type":"paragraph","content":[{"type":"text","text":"To kolejny dowód na to, że czeska i polska scena aufguss należą dziś do ścisłej światowej czołówki."}]}]}'::jsonb, null, null, 'published', now())
on conflict (slug) do nothing;

commit;

-- Podsumowanie: obiekty 107, saunamistrzowie 9, wydarzenia 25, turnieje 9, wpisy 19