-- ═══════════════════════════════════════════════════════════════════════════
--  aufguss.world — schemat bazy (Supabase / PostgreSQL)
--  Migracja 0001: typy, tabele, indeksy, wyzwalacze.
--  Polityki dostępu (RLS) są w migracji 0002.
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";

-- ── TYPY ────────────────────────────────────────────────────────────────────
-- Role odpowiadają dokładnie macierzy z panelu. 'user' i 'bloger' korzystają
-- z portalu, pozostałe z backendu.
create type app_role as enum (
  'user','bloger','saunamistrz','szkoleniowiec','sedzia','obiekt','organizator','admin'
);
create type role_status   as enum ('pending','active','rejected','revoked');
create type content_status as enum ('draft','review','published','hidden');
create type event_type    as enum ('ceremonia','noc-aufguss','turniej','szkolenie');
create type event_scope   as enum ('lokalne','krajowe','miedzynarodowe');
create type post_category as enum ('Recenzja','Wydarzenie','Aktualność','Felieton','Turnieje','Ceremonie','Społeczność','Obiekt');
create type cover_variant as enum ('pc1','pc2','pc3','pc4');
create type venue_member_role as enum ('admin','editor');

-- ── PROFILE ─────────────────────────────────────────────────────────────────
-- Rozszerza auth.users. Konto jest WIELOROLOWE — role trzyma osobna tabela.
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  slug         text unique,
  display_name text not null,
  bio          text,
  country      text,
  city         text,
  avatar_url   text,
  locale       text not null default 'pl',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table public.profiles is 'Konto użytkownika; role w user_roles (konta są wielorolowe).';

create table public.user_roles (
  id         bigint generated always as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role       app_role not null,
  status     role_status not null default 'active',
  granted_by uuid references public.profiles(id),
  granted_at timestamptz not null default now(),
  unique (profile_id, role)
);
create index on public.user_roles (profile_id) where status = 'active';

-- ── OBIEKTY ─────────────────────────────────────────────────────────────────
create table public.venues (
  id           bigint generated by default as identity primary key,
  slug         text unique not null,
  name         text not null,
  country      text not null,
  country_code text not null,                       -- kod flagi, np. 'pl'
  city         text,                                -- LUKA w danych: puste dla 107 obiektów z mapy
  lat          double precision,                    -- obiekt roboczy może nie mieć jeszcze współrzędnych
  lng          double precision,
  website      text,
  description  text,
  status       content_status not null default 'published',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- na mapę trafia tylko obiekt z pełną lokalizacją
  constraint venue_published_needs_coords
    check (status <> 'published' or (lat is not null and lng is not null))
);
create index on public.venues (country);
create index on public.venues (status);

-- Zespół obiektu — kilka osób może zarządzać jednym obiektem.
create table public.venue_members (
  venue_id   bigint not null references public.venues(id) on delete cascade,
  profile_id uuid   not null references public.profiles(id) on delete cascade,
  role       venue_member_role not null default 'editor',
  created_at timestamptz not null default now(),
  primary key (venue_id, profile_id)
);
create index on public.venue_members (profile_id);

-- ── SAUNAMISTRZOWIE ─────────────────────────────────────────────────────────
-- Byt, którego prototyp NIE MIAŁ (istnieli tylko jako napisy w wydarzeniach).
-- profile_id jest opcjonalne: mistrz może istnieć w bazie zanim założy konto.
create table public.saunamasters (
  id           bigint generated by default as identity primary key,
  profile_id   uuid unique references public.profiles(id) on delete set null,
  slug         text unique not null,
  name         text not null,
  country      text,
  country_code text,
  bio          text,
  rank         text,                                -- ranga turniejowa (Rookie…Pro Master)
  is_trainer   boolean not null default false,      -- odblokowuje moduł Szkolenia
  is_judge     boolean not null default false,
  status       content_status not null default 'published',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Saunamistrz występuje w WIELU obiektach; dokładnie jeden bywa macierzysty.
create table public.saunamaster_venues (
  saunamaster_id bigint not null references public.saunamasters(id) on delete cascade,
  venue_id       bigint not null references public.venues(id) on delete cascade,
  is_home        boolean not null default false,
  role           text,                              -- np. 'rezydent', 'gość'
  primary key (saunamaster_id, venue_id)
);
-- Twarda gwarancja: najwyżej jeden obiekt macierzysty na saunamistrza.
create unique index saunamaster_one_home
  on public.saunamaster_venues (saunamaster_id) where is_home;
create index on public.saunamaster_venues (venue_id);

-- ── WYDARZENIA ──────────────────────────────────────────────────────────────
create table public.events (
  id             bigint generated by default as identity primary key,
  slug           text unique,
  title          text not null,
  type           event_type not null,
  scope          event_scope not null default 'lokalne',
  starts_on      date not null,
  ends_on        date,
  venue_id       bigint references public.venues(id) on delete set null,
  description    text,
  ranking_points integer not null default 0,
  status         content_status not null default 'published',
  created_by     uuid references public.profiles(id),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint events_dates_ok check (ends_on is null or ends_on >= starts_on)
);
create index on public.events (starts_on);
create index on public.events (venue_id);

create table public.event_masters (
  event_id       bigint not null references public.events(id) on delete cascade,
  saunamaster_id bigint not null references public.saunamasters(id) on delete cascade,
  role           text,                              -- zawodnik / rezydent / gość / prowadzący
  primary key (event_id, saunamaster_id)
);
create index on public.event_masters (saunamaster_id);

-- ── TURNIEJE ────────────────────────────────────────────────────────────────
create table public.tournaments (
  id            bigint generated by default as identity primary key,
  slug          text unique not null,
  name          text not null,
  scope         event_scope not null,
  organizer     text,                               -- nazwa organizatora (docelowo FK)
  organizer_id  uuid references public.profiles(id),
  season        text,
  tagline       text,
  host_venue_id bigint references public.venues(id) on delete set null,
  status        content_status not null default 'published',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table public.tournament_stages (
  id            bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  position      integer not null default 0,
  label         text not null,
  description   text
);
create index on public.tournament_stages (tournament_id);

create table public.tournament_entries (
  id         bigint generated by default as identity primary key,
  stage_id   bigint not null references public.tournament_stages(id) on delete cascade,
  venue_id   bigint references public.venues(id) on delete set null,
  venue_name text,
  city       text,
  country    text,
  country_code text,
  starts_on  date,
  ends_on    date,
  highlight  boolean not null default false
);
create index on public.tournament_entries (stage_id);

create table public.tournament_results (
  id             bigint generated by default as identity primary key,
  tournament_id  bigint not null references public.tournaments(id) on delete cascade,
  year           integer not null,
  city           text,
  place          integer not null,
  saunamaster_id bigint references public.saunamasters(id) on delete set null,
  name           text not null,
  country        text,
  country_code   text,
  points         numeric(6,2),
  unique (tournament_id, year, place)
);

-- ── SZKOLENIA ───────────────────────────────────────────────────────────────
create table public.trainings (
  id             bigint generated by default as identity primary key,
  saunamaster_id bigint not null references public.saunamasters(id) on delete cascade,
  title          text not null,
  level          text,
  starts_on      date not null,
  venue_id       bigint references public.venues(id) on delete set null,
  place          text,
  seats_total    integer,
  seats_taken    integer not null default 0,
  description    text,
  status         content_status not null default 'published',
  created_at     timestamptz not null default now()
);
create index on public.trainings (saunamaster_id);

-- ── WPISY ───────────────────────────────────────────────────────────────────
-- body to dokument ProseMirror (JSONB) — ten sam schemat, którego pilnuje edytor
-- TipTap. Dzięki temu ograniczenia obowiązują też przy zapisie przez API.
create table public.posts (
  id             bigint generated by default as identity primary key,
  slug           text unique not null,
  author_id      uuid references public.profiles(id) on delete set null,
  venue_id       bigint references public.venues(id) on delete set null,  -- blog obiektu / recenzowany obiekt
  category       post_category not null,
  cover          cover_variant not null default 'pc1',
  title          text not null,
  lead           text,
  body           jsonb not null default '{"type":"doc","content":[]}'::jsonb,
  score          numeric(3,1) check (score is null or (score >= 1 and score <= 10)),
  status         content_status not null default 'draft',
  published_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- recenzja musi wskazywać obiekt i ocenę (z tego powstaje ranking blogera)
  constraint review_needs_venue_and_score
    check (category <> 'Recenzja' or (venue_id is not null and score is not null))
);
create index on public.posts (author_id);
create index on public.posts (status, published_at desc);

-- ── SPOŁECZNOŚĆ ─────────────────────────────────────────────────────────────
create table public.comments (
  id         bigint generated by default as identity primary key,
  post_id    bigint references public.posts(id) on delete cascade,
  venue_id   bigint references public.venues(id) on delete cascade,
  saunamaster_id bigint references public.saunamasters(id) on delete cascade,
  tournament_id  bigint references public.tournaments(id) on delete cascade,
  parent_id  bigint references public.comments(id) on delete cascade,
  author_id  uuid not null references public.profiles(id) on delete cascade,
  body       text not null,
  status     content_status not null default 'published',
  created_at timestamptz not null default now(),
  -- komentarz musi być przypięty dokładnie do jednego bytu
  constraint comment_single_target check (
    (post_id is not null)::int + (venue_id is not null)::int +
    (saunamaster_id is not null)::int + (tournament_id is not null)::int = 1
  )
);
create index on public.comments (post_id);
create index on public.comments (author_id);

create table public.follows (
  profile_id     uuid not null references public.profiles(id) on delete cascade,
  venue_id       bigint references public.venues(id) on delete cascade,
  saunamaster_id bigint references public.saunamasters(id) on delete cascade,
  tournament_id  bigint references public.tournaments(id) on delete cascade,
  created_at     timestamptz not null default now(),
  constraint follow_single_target check (
    (venue_id is not null)::int + (saunamaster_id is not null)::int + (tournament_id is not null)::int = 1
  )
);
create unique index follows_uniq on public.follows
  (profile_id, coalesce(venue_id,-1), coalesce(saunamaster_id,-1), coalesce(tournament_id,-1));

-- ── WNIOSKI O ROLE (kolejka moderacji) ──────────────────────────────────────
create table public.role_requests (
  id           bigint generated always as identity primary key,
  profile_id   uuid not null references public.profiles(id) on delete cascade,
  role         app_role not null,
  venue_id     bigint references public.venues(id) on delete set null,  -- wniosek o zarządzanie obiektem
  message      text,
  status       role_status not null default 'pending',
  decided_by   uuid references public.profiles(id),
  decided_at   timestamptz,
  created_at   timestamptz not null default now()
);
create index on public.role_requests (status, created_at);

-- ── AUTOMATY ────────────────────────────────────────────────────────────────
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['profiles','venues','saunamasters','events','tournaments','posts']
  loop
    execute format(
      'create trigger %I_touch before update on public.%I
         for each row execute function public.touch_updated_at()', t, t);
  end loop;
end $$;

-- Nowe konto w auth.users automatycznie dostaje profil i rolę 'user'.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)));
  insert into public.user_roles (profile_id, role) values (new.id, 'user');
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
