-- ═══════════════════════════════════════════════════════════════════════════
--  aufguss.world — zgłoszenia uwag do treści (migracja 0004)
--
--  ZAŁOŻENIE: przy 17 językach nikt nie zatwierdzi treści przed publikacją.
--  Agent AI tłumaczy i PUBLIKUJE OD RAZU (status 'machine'), a jakości pilnują
--  czytelnicy — każdy widok ma „Zgłoś uwagę". Zgłoszenie nie idzie do wspólnego
--  worka administratora, tylko trafia WPROST do właściciela danej treści:
--    · uwaga do obiektu / wydarzenia  → zespół tego obiektu
--    · uwaga do wpisu                 → autor wpisu
--    · uwaga do szkolenia             → prowadzący saunamistrz
--    · uwaga do turnieju              → organizator
--    · uwaga do komentarza            → administrator (moderacja)
--  Kierowanie wylicza wyzwalacz przy zapisie — zgłaszający nie musi wiedzieć, kto odpowiada.
-- ═══════════════════════════════════════════════════════════════════════════

create type report_kind as enum (
  'tlumaczenie',        -- błąd lub nienaturalny język w tłumaczeniu
  'nieaktualne',        -- obiekt zamknięty, wydarzenie odwołane, zmiana godzin
  'blad-merytoryczny',  -- nieprawdziwa informacja
  'literowka',
  'niestosowne',        -- treść narusza zasady
  'inne'
);
create type report_status as enum ('new','in_progress','resolved','rejected');

create table public.content_reports (
  id            bigint generated by default as identity primary key,

  -- czego dotyczy uwaga (dokładnie jeden byt)
  venue_id      bigint references public.venues(id)       on delete cascade,
  event_id      bigint references public.events(id)       on delete cascade,
  post_id       bigint references public.posts(id)        on delete cascade,
  training_id   bigint references public.trainings(id)    on delete cascade,
  tournament_id bigint references public.tournaments(id)  on delete cascade,
  comment_id    bigint references public.comments(id)     on delete cascade,

  -- której wersji językowej dotyczy; null = uwaga do oryginału, nie do tłumaczenia
  locale        text references public.locales(code),

  kind          report_kind not null default 'inne',
  message       text,

  reporter_id    uuid references public.profiles(id) on delete set null,
  reporter_email text,                       -- dla niezalogowanych

  -- KIEROWANIE — wyliczane wyzwalaczem, nie podawane przez zgłaszającego
  route_venue_id      bigint references public.venues(id)      on delete set null,
  route_profile_id    uuid   references public.profiles(id)    on delete set null,
  route_tournament_id bigint references public.tournaments(id) on delete set null,

  status          report_status not null default 'new',
  resolution_note text,
  resolved_by     uuid references public.profiles(id),
  resolved_at     timestamptz,
  created_at      timestamptz not null default now(),

  constraint report_single_target check (
    (venue_id is not null)::int + (event_id is not null)::int + (post_id is not null)::int +
    (training_id is not null)::int + (tournament_id is not null)::int + (comment_id is not null)::int = 1
  ),
  -- anonim musi zostawić kontakt, żeby dało się dopytać
  constraint report_has_reporter check (reporter_id is not null or reporter_email is not null)
);
create index on public.content_reports (status, created_at desc);
create index on public.content_reports (route_venue_id)   where route_venue_id is not null;
create index on public.content_reports (route_profile_id) where route_profile_id is not null;

-- ── KIEROWANIE ZGŁOSZENIA DO WŁAŚCIWEJ OSOBY ────────────────────────────────
create or replace function public.route_content_report()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.route_venue_id := null;
  new.route_profile_id := null;
  new.route_tournament_id := null;

  if new.venue_id is not null then
    new.route_venue_id := new.venue_id;                      -- zespół obiektu

  elsif new.event_id is not null then
    select e.venue_id into new.route_venue_id                -- obiekt, w którym trwa wydarzenie
    from public.events e where e.id = new.event_id;

  elsif new.post_id is not null then
    select p.author_id, p.venue_id into new.route_profile_id, new.route_venue_id
    from public.posts p where p.id = new.post_id;            -- autor, a dla bloga obiektu też obiekt

  elsif new.training_id is not null then
    select s.profile_id into new.route_profile_id            -- prowadzący saunamistrz
    from public.trainings t join public.saunamasters s on s.id = t.saunamaster_id
    where t.id = new.training_id;

  elsif new.tournament_id is not null then
    select t.id, t.organizer_id into new.route_tournament_id, new.route_profile_id
    from public.tournaments t where t.id = new.tournament_id;

  end if;
  -- uwaga do komentarza nie ma właściciela treści → zostaje administratorowi
  return new;
end $$;

create trigger content_reports_route
  before insert or update of venue_id, event_id, post_id, training_id, tournament_id, comment_id
  on public.content_reports
  for each row execute function public.route_content_report();

-- ── UNIEWAŻNIENIE TŁUMACZENIA ───────────────────────────────────────────────
-- Gdy uwaga dotyczy tłumaczenia i zostanie uznana, kasujemy je: widok
-- translation_queue natychmiast pokaże brak, więc agent przetłumaczy od nowa.
create or replace function public.invalidate_translation(p_report_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare r public.content_reports;
begin
  select * into r from public.content_reports where id = p_report_id;
  if r.locale is null then return; end if;

  if    r.venue_id      is not null then delete from public.venue_translations      where venue_id = r.venue_id and locale = r.locale;
  elsif r.event_id      is not null then delete from public.event_translations      where event_id = r.event_id and locale = r.locale;
  elsif r.post_id       is not null then delete from public.post_translations       where post_id = r.post_id and locale = r.locale;
  elsif r.training_id   is not null then delete from public.training_translations   where training_id = r.training_id and locale = r.locale;
  elsif r.tournament_id is not null then delete from public.tournament_translations where tournament_id = r.tournament_id and locale = r.locale;
  end if;
end $$;
comment on function public.invalidate_translation is
  'Usuwa zakwestionowane tłumaczenie — pozycja wraca do translation_queue i agent tłumaczy ponownie.';

-- ── KTO CO WIDZI ────────────────────────────────────────────────────────────
alter table public.content_reports enable row level security;

-- Zgłaszać może każdy, także niezalogowany (wtedy z adresem e-mail).
-- Kierowania nie da się podmienić — i tak nadpisuje je wyzwalacz.
create policy cr_insert on public.content_reports for insert
  with check (reporter_id is null or reporter_id = auth.uid());

-- Widzi: zgłaszający swoje, właściciel treści swoje, administrator wszystkie.
create policy cr_read on public.content_reports for select using (
  reporter_id = auth.uid()
  or public.is_admin()
  or (route_venue_id is not null and public.manages_venue(route_venue_id))
  or (route_profile_id = auth.uid())
  or (route_tournament_id is not null and exists (
        select 1 from public.tournaments t
        where t.id = route_tournament_id and t.organizer_id = auth.uid()))
);

-- Rozstrzyga właściciel treści albo administrator (zgłaszający już nie).
create policy cr_update on public.content_reports for update using (
  public.is_admin()
  or (route_venue_id is not null and public.manages_venue(route_venue_id))
  or (route_profile_id = auth.uid())
  or (route_tournament_id is not null and exists (
        select 1 from public.tournaments t
        where t.id = route_tournament_id and t.organizer_id = auth.uid()))
) with check (
  public.is_admin()
  or (route_venue_id is not null and public.manages_venue(route_venue_id))
  or (route_profile_id = auth.uid())
  or (route_tournament_id is not null and exists (
        select 1 from public.tournaments t
        where t.id = route_tournament_id and t.organizer_id = auth.uid()))
);

-- ── SKRZYNKA ZGŁOSZEŃ DO PANELU ─────────────────────────────────────────────
-- security_invoker: widok respektuje RLS pytającego, więc każdy widzi tylko swoje.
create or replace view public.my_content_reports
with (security_invoker = true) as
  select r.id, r.kind, r.status, r.locale, r.message, r.created_at,
         case
           when r.venue_id      is not null then 'obiekt'
           when r.event_id      is not null then 'wydarzenie'
           when r.post_id       is not null then 'wpis'
           when r.training_id   is not null then 'szkolenie'
           when r.tournament_id is not null then 'turniej'
           else 'komentarz'
         end as target_kind,
         coalesce(v.name, e.title, p.title, tr.title, tn.name) as target_name,
         coalesce(v.id, e.venue_id) as venue_id,
         (r.locale is not null) as is_translation_issue
  from public.content_reports r
  left join public.venues      v  on v.id  = r.venue_id
  left join public.events      e  on e.id  = r.event_id
  left join public.posts       p  on p.id  = r.post_id
  left join public.trainings   tr on tr.id = r.training_id
  left join public.tournaments tn on tn.id = r.tournament_id;

-- ── JAWNA ZASADA PUBLIKACJI ─────────────────────────────────────────────────
comment on type translation_status is
  'machine = wynik agenta AI, publikowany OD RAZU (bez zatwierdzania — przy 17 językach '
  'weryfikacja z góry jest niewykonalna); reviewed = sprawdzone po zgłoszeniu uwagi; '
  'human = tłumaczone lub poprawione ręcznie.';
