-- ═══════════════════════════════════════════════════════════════════════════
--  aufguss.world — ochrona zgłoszeń przed nadużyciami (migracja 0005)
--
--  Zgłaszać może każdy, także niezalogowany — to celowe, bo błąd w tłumaczeniu
--  najczęściej zauważy przypadkowy czytelnik. Ale otwarta skrzynka jest łakomym
--  celem: wystarczy zalać właściciela obiektu spamem, żeby przestał ją czytać.
--
--  Cztery warstwy, od najtańszej do najostrzejszej:
--   1. LIMIT CZASOWY   — ile zgłoszeń na dobę z jednego konta / adresu
--   2. BEZ DUPLIKATÓW  — jedno otwarte zgłoszenie do tej samej treści i wersji
--   3. REPUTACJA       — kto zgłasza trafnie, a kto tylko hałasuje
--   4. BLOKADA         — czasowa lub bezterminowa, ręczna albo automatyczna
--
--  Świadomie NIE blokujemy po adresie IP — w bazie go nie trzymamy (RODO),
--  a i tak łatwo go zmienić. Warstwa aplikacji powinna dołożyć CAPTCHA
--  dla niezalogowanych oraz limit po IP na brzegu sieci.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── BLOKADY ZGŁASZAJĄCYCH ───────────────────────────────────────────────────
create table public.report_blocks (
  id          bigint generated by default as identity primary key,
  profile_id  uuid references public.profiles(id) on delete cascade,
  email       text,                              -- dla niezalogowanych
  reason      text not null,
  blocked_until timestamptz,                     -- null = bezterminowo
  is_automatic  boolean not null default false,
  created_by  uuid references public.profiles(id),
  created_at  timestamptz not null default now(),
  constraint block_has_subject check (profile_id is not null or email is not null)
);
create unique index report_blocks_profile on public.report_blocks (profile_id) where profile_id is not null;
create unique index report_blocks_email   on public.report_blocks (lower(email)) where email is not null;

create or replace function public.is_report_blocked(p_profile uuid, p_email text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.report_blocks b
    where (blocked_until is null or blocked_until > now())
      and ((p_profile is not null and b.profile_id = p_profile)
        or (p_email  is not null and lower(b.email) = lower(p_email)))
  );
$$;

-- ── LIMITY ──────────────────────────────────────────────────────────────────
-- Zalogowanym ufamy bardziej: mają co stracić. Anonim dostaje ostrzejszy limit.
create table public.report_limits (
  scope        text primary key,                 -- 'authenticated' | 'anonymous'
  per_day      integer not null,
  per_week     integer not null
);
insert into public.report_limits (scope, per_day, per_week) values
  ('authenticated', 10, 30),
  ('anonymous',      3, 10);

-- ── STRAŻNIK PRZY ZAPISIE ───────────────────────────────────────────────────
create or replace function public.guard_content_report()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_scope text;
  v_day   integer;
  v_week  integer;
  v_cnt   integer;
begin
  new.reporter_email := nullif(lower(trim(new.reporter_email)), '');

  -- 1. blokada
  if public.is_report_blocked(new.reporter_id, new.reporter_email) then
    raise exception 'Zgłoszenia z tego konta zostały wstrzymane.'
      using errcode = 'check_violation', hint = 'report_blocked';
  end if;

  -- 2. limit dobowy i tygodniowy
  v_scope := case when new.reporter_id is not null then 'authenticated' else 'anonymous' end;
  select per_day, per_week into v_day, v_week from public.report_limits where scope = v_scope;

  select count(*) into v_cnt from public.content_reports r
  where r.created_at > now() - interval '1 day'
    and ((new.reporter_id is not null and r.reporter_id = new.reporter_id)
      or (new.reporter_id is null and r.reporter_email = new.reporter_email));
  if v_cnt >= v_day then
    raise exception 'Dzienny limit zgłoszeń (%) został wyczerpany. Spróbuj jutro.', v_day
      using errcode = 'check_violation', hint = 'rate_limit_day';
  end if;

  select count(*) into v_cnt from public.content_reports r
  where r.created_at > now() - interval '7 days'
    and ((new.reporter_id is not null and r.reporter_id = new.reporter_id)
      or (new.reporter_id is null and r.reporter_email = new.reporter_email));
  if v_cnt >= v_week then
    raise exception 'Tygodniowy limit zgłoszeń (%) został wyczerpany.', v_week
      using errcode = 'check_violation', hint = 'rate_limit_week';
  end if;

  -- 3. bez duplikatów: jedno OTWARTE zgłoszenie do tej samej treści i wersji językowej
  select count(*) into v_cnt from public.content_reports r
  where r.status in ('new','in_progress')
    and r.locale is not distinct from new.locale
    and r.venue_id is not distinct from new.venue_id
    and r.event_id is not distinct from new.event_id
    and r.post_id is not distinct from new.post_id
    and r.training_id is not distinct from new.training_id
    and r.tournament_id is not distinct from new.tournament_id
    and r.comment_id is not distinct from new.comment_id
    and ((new.reporter_id is not null and r.reporter_id = new.reporter_id)
      or (new.reporter_id is null and r.reporter_email = new.reporter_email));
  if v_cnt > 0 then
    raise exception 'Zgłosiłeś już tę treść — uwaga czeka na rozpatrzenie.'
      using errcode = 'unique_violation', hint = 'duplicate_report';
  end if;

  return new;
end $$;

create trigger content_reports_guard
  before insert on public.content_reports
  for each row execute function public.guard_content_report();

-- ── REPUTACJA ZGŁASZAJĄCEGO ─────────────────────────────────────────────────
-- Właściciel treści widzi, czy ma do czynienia z kimś, kto zwykle trafia,
-- czy z kimś, komu odrzucono już wszystko. To zmienia sposób czytania uwagi.
create or replace view public.reporter_reputation as
  select
    r.reporter_id,
    r.reporter_email,
    count(*)                                              as zgloszen,
    count(*) filter (where r.status = 'resolved')          as potwierdzonych,
    count(*) filter (where r.status = 'rejected')          as odrzuconych,
    count(*) filter (where r.status in ('new','in_progress')) as otwartych,
    case when count(*) filter (where r.status in ('resolved','rejected')) = 0 then null
         else round(100.0 * count(*) filter (where r.status = 'resolved')
                    / count(*) filter (where r.status in ('resolved','rejected')))
    end                                                    as trafnosc_proc
  from public.content_reports r
  group by r.reporter_id, r.reporter_email;

-- ── AUTOMATYCZNA BLOKADA ────────────────────────────────────────────────────
-- Po odrzuceniu zgłoszenia sprawdzamy dorobek autora. Pięć odrzuceń bez ani
-- jednego trafienia = 30 dni przerwy. Wystarczy JEDNO potwierdzone zgłoszenie,
-- żeby automat nie zadziałał — nie karzemy ludzi, którzy czasem się mylą.
create or replace function public.autoblock_after_rejections()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_rej integer; v_ok integer;
begin
  if new.status <> 'rejected' or old.status = 'rejected' then return new; end if;

  select count(*) filter (where status = 'rejected'),
         count(*) filter (where status = 'resolved')
    into v_rej, v_ok
  from public.content_reports
  where (new.reporter_id is not null and reporter_id = new.reporter_id)
     or (new.reporter_id is null and reporter_email = new.reporter_email);

  if v_rej >= 5 and v_ok = 0 then
    insert into public.report_blocks (profile_id, email, reason, blocked_until, is_automatic)
    values (new.reporter_id, new.reporter_email,
            format('Automat: %s odrzuconych zgłoszeń bez potwierdzonego.', v_rej),
            now() + interval '30 days', true)
    on conflict do nothing;
  end if;
  return new;
end $$;

create trigger content_reports_autoblock
  after update of status on public.content_reports
  for each row execute function public.autoblock_after_rejections();

-- ── CZUJKA NADUŻYĆ PO DRUGIEJ STRONIE ───────────────────────────────────────
-- Uwaga: właściciel treści też może nadużywać — odrzucać wszystko, żeby uciszyć
-- niewygodne uwagi. Administrator powinien to widzieć.
create or replace view public.report_rejection_watch as
  select
    coalesce(v.name, t.name, 'treść osobista')            as obszar,
    r.route_venue_id, r.route_profile_id, r.route_tournament_id,
    count(*)                                              as rozpatrzonych,
    count(*) filter (where r.status = 'rejected')          as odrzuconych,
    round(100.0 * count(*) filter (where r.status = 'rejected') / nullif(count(*),0)) as odrzucen_proc
  from public.content_reports r
  left join public.venues v      on v.id = r.route_venue_id
  left join public.tournaments t on t.id = r.route_tournament_id
  where r.status in ('resolved','rejected')
  group by 1, r.route_venue_id, r.route_profile_id, r.route_tournament_id
  having count(*) >= 5
     and count(*) filter (where r.status = 'rejected') * 2 > count(*);   -- ponad połowa odrzucona

-- ── DOSTĘP ──────────────────────────────────────────────────────────────────
alter table public.report_blocks enable row level security;
alter table public.report_limits enable row level security;

-- Blokady widzi i nakłada wyłącznie administrator; zablokowany widzi swoją.
create policy rb_read on public.report_blocks for select
  using (public.is_admin() or profile_id = auth.uid());
create policy rb_write on public.report_blocks for all
  using (public.is_admin()) with check (public.is_admin());

create policy rl_read  on public.report_limits for select using (true);
create policy rl_write on public.report_limits for all
  using (public.is_admin()) with check (public.is_admin());

comment on table public.report_blocks is
  'Wstrzymanie zgłoszeń. Automat nakłada 30 dni po 5 odrzuceniach bez trafienia; administrator może nałożyć bezterminowo.';
comment on view  public.report_rejection_watch is
  'Właściciele odrzucający ponad połowę zgłoszeń — do przeglądu przez administratora.';
